# psx_sequence.ps1
# Drives GIMP's native dialogs in sequence: Scale -> RGB Noise -> Indexed -> Gaussian Blur.
# Keyboard shortcuts are read from psx_keys.txt (generated by install.ps1).

param(
    [int]$StepTimeout = 30,
    [int]$PollMs      = 150
)

$keysFile = Join-Path $PSScriptRoot 'psx_keys.txt'
if (-not (Test-Path $keysFile)) {
    Add-Type -AssemblyName System.Windows.Forms
    [System.Windows.Forms.MessageBox]::Show(
        "psx_keys.txt not found.`nPlease run install.ps1 (or install.bat) first.",
        'PSX Sequence', 'OK', 'Error') | Out-Null
    exit 1
}

$keys = Get-Content $keysFile | Where-Object { $_.Trim() -ne '' }
if ($keys.Count -lt 4) {
    Add-Type -AssemblyName System.Windows.Forms
    [System.Windows.Forms.MessageBox]::Show(
        "psx_keys.txt is incomplete. Please re-run install.ps1.",
        'PSX Sequence', 'OK', 'Error') | Out-Null
    exit 1
}

$stepKeys = @{
    'Scale Image'    = $keys[0]
    'RGB Noise'      = $keys[1]
    'Convert Indexed'= $keys[2]
    'Gaussian Blur'  = $keys[3]
}

Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

public class WinApi {
    public delegate bool EnumWindowsProc(IntPtr hwnd, IntPtr lParam);

    [DllImport("user32.dll")] public static extern bool EnumWindows(EnumWindowsProc lpEnumFunc, IntPtr lParam);
    [DllImport("user32.dll")] public static extern bool IsWindowVisible(IntPtr hwnd);
    [DllImport("user32.dll")] public static extern bool IsWindow(IntPtr hwnd);
    [DllImport("user32.dll")] public static extern int  GetWindowText(IntPtr hwnd, StringBuilder sb, int maxCount);
    [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr hwnd, out uint lpdwProcessId);
    [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hwnd);
    [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hwnd, int nCmdShow);

    public static List<long> GetVisibleWindowsForPid(uint pid, long excludeHwnd) {
        var list = new List<long>();
        EnumWindows((hwnd, _) => {
            if (!IsWindowVisible(hwnd)) return true;
            uint wpid;
            GetWindowThreadProcessId(hwnd, out wpid);
            if (wpid == pid && hwnd.ToInt64() != excludeHwnd) {
                var sb = new StringBuilder(256);
                GetWindowText(hwnd, sb, 256);
                if (sb.Length > 0) list.Add(hwnd.ToInt64());
            }
            return true;
        }, IntPtr.Zero);
        return list;
    }
}
'@

Add-Type -AssemblyName System.Windows.Forms

$gimpProc = Get-Process -Name 'gimp-3*','gimp*' -ErrorAction SilentlyContinue |
            Where-Object { $_.MainWindowHandle -ne [IntPtr]::Zero } |
            Select-Object -First 1

if (-not $gimpProc) {
    [System.Windows.Forms.MessageBox]::Show(
        "GIMP is not open or has no visible window.",
        'PSX Sequence', 'OK', 'Error') | Out-Null
    exit 1
}

$pid_gimp  = [uint32]$gimpProc.Id
$mainHwnd  = $gimpProc.MainWindowHandle.ToInt64()

function Get-GimpDialogs {
    return [WinApi]::GetVisibleWindowsForPid($pid_gimp, $mainHwnd)
}

function Focus-Gimp {
    [WinApi]::ShowWindow([IntPtr]$mainHwnd, 9) | Out-Null
    [WinApi]::SetForegroundWindow([IntPtr]$mainHwnd) | Out-Null
    Start-Sleep -Milliseconds 400
}

function Send-StepAndWait {
    param([string]$SendKey, [string]$StepName)

    Write-Host ">>> $StepName ..."
    Focus-Gimp

    $before = @(Get-GimpDialogs)

    [System.Windows.Forms.SendKeys]::SendWait($SendKey)

    $deadline = (Get-Date).AddSeconds($StepTimeout)
    $newHwnd  = $null
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Milliseconds $PollMs
        $after = @(Get-GimpDialogs)
        $diff  = $after | Where-Object { $before -notcontains $_ }
        if ($diff) { $newHwnd = $diff[0]; break }
    }

    if (-not $newHwnd) {
        [System.Windows.Forms.MessageBox]::Show(
            "Timeout: '$StepName' dialog did not open.`n`nMake sure the keyboard shortcut '$SendKey' is assigned in GIMP.",
            "PSX Sequence — $StepName", 'OK', 'Warning') | Out-Null
        return
    }

    Write-Host "    Dialog open (HWND $newHwnd). Waiting for you to close it..."

    while ([WinApi]::IsWindow([IntPtr]$newHwnd) -and [WinApi]::IsWindowVisible([IntPtr]$newHwnd)) {
        Start-Sleep -Milliseconds $PollMs
    }

    Write-Host "    $StepName done."
    Start-Sleep -Milliseconds 300
}

Write-Host "=== PSX Sequence started ==="
Send-StepAndWait $stepKeys['Scale Image']     'Scale Image'
Send-StepAndWait $stepKeys['RGB Noise']       'RGB Noise'
Send-StepAndWait $stepKeys['Convert Indexed'] 'Convert to Indexed'
Send-StepAndWait $stepKeys['Gaussian Blur']   'Gaussian Blur'
Write-Host "=== PSX Sequence complete! ==="
